/**
 * generated by Xtext 2.12.0
 */
package org.xtext.formatting2;

import com.google.inject.Inject;
import java.util.Arrays;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.formatting2.AbstractFormatter2;
import org.eclipse.xtext.formatting2.IFormattableDocument;
import org.eclipse.xtext.resource.XtextResource;
import org.eclipse.xtext.xbase.lib.Extension;
import org.xtext.services.UpctformagamiGrammarAccess;
import upctformagami.Badge;
import upctformagami.Gamification;
import upctformagami.Import;
import upctformagami.PointAchievement;
import upctformagami.UnitGamify;
import upctformagami.WidgetGamify;

@SuppressWarnings("all")
public class UpctformagamiFormatter extends AbstractFormatter2 {
  @Inject
  @Extension
  private UpctformagamiGrammarAccess _upctformagamiGrammarAccess;
  
  protected void _format(final Gamification gamification, @Extension final IFormattableDocument document) {
    EList<Import> _imports = gamification.getImports();
    for (final Import _import : _imports) {
      document.<Import>format(_import);
    }
    EList<Badge> _badges = gamification.getBadges();
    for (final Badge badge : _badges) {
      document.<Badge>format(badge);
    }
    EList<WidgetGamify> _widgets = gamification.getWidgets();
    for (final WidgetGamify widgetGamify : _widgets) {
      document.<WidgetGamify>format(widgetGamify);
    }
    EList<UnitGamify> _units = gamification.getUnits();
    for (final UnitGamify unitGamify : _units) {
      document.<UnitGamify>format(unitGamify);
    }
  }
  
  protected void _format(final WidgetGamify widgetGamify, @Extension final IFormattableDocument document) {
    EList<PointAchievement> _pointswidgetdef = widgetGamify.getPointswidgetdef();
    for (final PointAchievement pointAchievement : _pointswidgetdef) {
      document.<PointAchievement>format(pointAchievement);
    }
  }
  
  public void format(final Object gamification, final IFormattableDocument document) {
    if (gamification instanceof XtextResource) {
      _format((XtextResource)gamification, document);
      return;
    } else if (gamification instanceof Gamification) {
      _format((Gamification)gamification, document);
      return;
    } else if (gamification instanceof WidgetGamify) {
      _format((WidgetGamify)gamification, document);
      return;
    } else if (gamification instanceof EObject) {
      _format((EObject)gamification, document);
      return;
    } else if (gamification == null) {
      _format((Void)null, document);
      return;
    } else if (gamification != null) {
      _format(gamification, document);
      return;
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(gamification, document).toString());
    }
  }
}
