/*
 * generated by Xtext 2.12.0
 */
package org.xtext.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.parser.antlr.internal.InternalUpctformaParser;
import org.xtext.services.UpctformaGrammarAccess;

public class UpctformaParser extends AbstractAntlrParser {

	@Inject
	private UpctformaGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalUpctformaParser createParser(XtextTokenStream stream) {
		return new InternalUpctformaParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "ContentDefinition";
	}

	public UpctformaGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(UpctformaGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
