/**
 * generated by Xtext 2.12.0
 */
package org.xtext.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.UpctformaevaluaRuntimeModule;
import org.xtext.UpctformaevaluaStandaloneSetup;
import org.xtext.ide.UpctformaevaluaIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class UpctformaevaluaIdeSetup extends UpctformaevaluaStandaloneSetup {
  @Override
  public Injector createInjector() {
    UpctformaevaluaRuntimeModule _upctformaevaluaRuntimeModule = new UpctformaevaluaRuntimeModule();
    UpctformaevaluaIdeModule _upctformaevaluaIdeModule = new UpctformaevaluaIdeModule();
    return Guice.createInjector(Modules2.mixin(_upctformaevaluaRuntimeModule, _upctformaevaluaIdeModule));
  }
}
