/**
 * generated by Xtext 2.12.0
 */
package org.xtext.ide;

import org.xtext.ide.AbstractUpctformaevaluaIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class UpctformaevaluaIdeModule extends AbstractUpctformaevaluaIdeModule {
}
