/*
 * generated by Xtext 2.12.0
 */
package org.xtext.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.upctformaevalua.ui.internal.UpctformaevaluaActivator;

public class UpctformaevaluaUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return UpctformaevaluaActivator.getInstance().getInjector("org.xtext.Upctformaevalua");
	}

}
