/*
 * generated by Xtext 2.12.0
 */
package org.xtext.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.EnumLiteralDeclaration;
import org.eclipse.xtext.EnumRule;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractEnumRuleElementFinder;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class UpctformaevaluaGrammarAccess extends AbstractGrammarElementFinder {
	
	public class EvaluationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.Upctformaevalua.Evaluation");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cEvaluationAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cEvaluationKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cPackageKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cNameAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cNameQualifiedNameParserRuleCall_4_1_0 = (RuleCall)cNameAssignment_4_1.eContents().get(0);
		private final Keyword cSemicolonKeyword_4_2 = (Keyword)cGroup_4.eContents().get(2);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Assignment cUnitsAssignment_5_0 = (Assignment)cGroup_5.eContents().get(0);
		private final RuleCall cUnitsEvaluationUnitParserRuleCall_5_0_0 = (RuleCall)cUnitsAssignment_5_0.eContents().get(0);
		private final Group cGroup_5_1 = (Group)cGroup_5.eContents().get(1);
		private final Keyword cCommaKeyword_5_1_0 = (Keyword)cGroup_5_1.eContents().get(0);
		private final Assignment cUnitsAssignment_5_1_1 = (Assignment)cGroup_5_1.eContents().get(1);
		private final RuleCall cUnitsEvaluationUnitParserRuleCall_5_1_1_0 = (RuleCall)cUnitsAssignment_5_1_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//Evaluation:
		//	{Evaluation}
		//	'Evaluation'
		//	name=EString
		//	'{' ('package' name=QualifiedName ';')? (units+=EvaluationUnit ("," units+=EvaluationUnit)*)?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Evaluation} 'Evaluation' name=EString '{' ('package' name=QualifiedName ';')? (units+=EvaluationUnit (","
		//units+=EvaluationUnit)*)? '}'
		public Group getGroup() { return cGroup; }
		
		//{Evaluation}
		public Action getEvaluationAction_0() { return cEvaluationAction_0; }
		
		//'Evaluation'
		public Keyword getEvaluationKeyword_1() { return cEvaluationKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('package' name=QualifiedName ';')?
		public Group getGroup_4() { return cGroup_4; }
		
		//'package'
		public Keyword getPackageKeyword_4_0() { return cPackageKeyword_4_0; }
		
		//name=QualifiedName
		public Assignment getNameAssignment_4_1() { return cNameAssignment_4_1; }
		
		//QualifiedName
		public RuleCall getNameQualifiedNameParserRuleCall_4_1_0() { return cNameQualifiedNameParserRuleCall_4_1_0; }
		
		//';'
		public Keyword getSemicolonKeyword_4_2() { return cSemicolonKeyword_4_2; }
		
		//(units+=EvaluationUnit ("," units+=EvaluationUnit)*)?
		public Group getGroup_5() { return cGroup_5; }
		
		//units+=EvaluationUnit
		public Assignment getUnitsAssignment_5_0() { return cUnitsAssignment_5_0; }
		
		//EvaluationUnit
		public RuleCall getUnitsEvaluationUnitParserRuleCall_5_0_0() { return cUnitsEvaluationUnitParserRuleCall_5_0_0; }
		
		//("," units+=EvaluationUnit)*
		public Group getGroup_5_1() { return cGroup_5_1; }
		
		//","
		public Keyword getCommaKeyword_5_1_0() { return cCommaKeyword_5_1_0; }
		
		//units+=EvaluationUnit
		public Assignment getUnitsAssignment_5_1_1() { return cUnitsAssignment_5_1_1; }
		
		//EvaluationUnit
		public RuleCall getUnitsEvaluationUnitParserRuleCall_5_1_1_0() { return cUnitsEvaluationUnitParserRuleCall_5_1_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class QualifiedNameElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.Upctformaevalua.QualifiedName");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cIDTerminalRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cFullStopKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1_1 = (RuleCall)cGroup_1.eContents().get(1);
		
		//QualifiedName:
		//	ID ('.' ID)*;
		@Override public ParserRule getRule() { return rule; }
		
		//ID ('.' ID)*
		public Group getGroup() { return cGroup; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_0() { return cIDTerminalRuleCall_0; }
		
		//('.' ID)*
		public Group getGroup_1() { return cGroup_1; }
		
		//'.'
		public Keyword getFullStopKeyword_1_0() { return cFullStopKeyword_1_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1_1() { return cIDTerminalRuleCall_1_1; }
	}
	public class EvaluationUnitElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.Upctformaevalua.EvaluationUnit");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cEvaluationUnit_ImplParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cTrainingParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cFinalParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		//EvaluationUnit:
		//	EvaluationUnit_Impl | Training | Final;
		@Override public ParserRule getRule() { return rule; }
		
		//EvaluationUnit_Impl | Training | Final
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//EvaluationUnit_Impl
		public RuleCall getEvaluationUnit_ImplParserRuleCall_0() { return cEvaluationUnit_ImplParserRuleCall_0; }
		
		//Training
		public RuleCall getTrainingParserRuleCall_1() { return cTrainingParserRuleCall_1; }
		
		//Final
		public RuleCall getFinalParserRuleCall_2() { return cFinalParserRuleCall_2; }
	}
	public class QuestionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.Upctformaevalua.Question");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cQuestion_ImplParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cUniqueAnswerParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cMultipleAnswerParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cFillingAnswerParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		private final RuleCall cTrueOrFalseParserRuleCall_4 = (RuleCall)cAlternatives.eContents().get(4);
		
		//Question:
		//	Question_Impl | UniqueAnswer | MultipleAnswer | FillingAnswer | TrueOrFalse;
		@Override public ParserRule getRule() { return rule; }
		
		//Question_Impl | UniqueAnswer | MultipleAnswer | FillingAnswer | TrueOrFalse
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Question_Impl
		public RuleCall getQuestion_ImplParserRuleCall_0() { return cQuestion_ImplParserRuleCall_0; }
		
		//UniqueAnswer
		public RuleCall getUniqueAnswerParserRuleCall_1() { return cUniqueAnswerParserRuleCall_1; }
		
		//MultipleAnswer
		public RuleCall getMultipleAnswerParserRuleCall_2() { return cMultipleAnswerParserRuleCall_2; }
		
		//FillingAnswer
		public RuleCall getFillingAnswerParserRuleCall_3() { return cFillingAnswerParserRuleCall_3; }
		
		//TrueOrFalse
		public RuleCall getTrueOrFalseParserRuleCall_4() { return cTrueOrFalseParserRuleCall_4; }
	}
	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.Upctformaevalua.EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString:
		//	STRING | ID;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}
	public class EvaluationUnit_ImplElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.Upctformaevalua.EvaluationUnit_Impl");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cEvaluationUnitAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cEvaluationUnitKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cNumberquestionsKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cNumberquestionsAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cNumberquestionsEIntParserRuleCall_4_1_0 = (RuleCall)cNumberquestionsAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cQuestionsKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cQuestionsAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final RuleCall cQuestionsQuestionParserRuleCall_5_2_0 = (RuleCall)cQuestionsAssignment_5_2.eContents().get(0);
		private final Group cGroup_5_3 = (Group)cGroup_5.eContents().get(3);
		private final Keyword cCommaKeyword_5_3_0 = (Keyword)cGroup_5_3.eContents().get(0);
		private final Assignment cQuestionsAssignment_5_3_1 = (Assignment)cGroup_5_3.eContents().get(1);
		private final RuleCall cQuestionsQuestionParserRuleCall_5_3_1_0 = (RuleCall)cQuestionsAssignment_5_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5_4 = (Keyword)cGroup_5.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//EvaluationUnit_Impl EvaluationUnit:
		//	{EvaluationUnit}
		//	'EvaluationUnit'
		//	name=EString
		//	'{' ('numberquestions' numberquestions=EInt)? ('questions' '{' questions+=Question ("," questions+=Question)* '}')?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{EvaluationUnit} 'EvaluationUnit' name=EString '{' ('numberquestions' numberquestions=EInt)? ('questions' '{'
		//questions+=Question ("," questions+=Question)* '}')? '}'
		public Group getGroup() { return cGroup; }
		
		//{EvaluationUnit}
		public Action getEvaluationUnitAction_0() { return cEvaluationUnitAction_0; }
		
		//'EvaluationUnit'
		public Keyword getEvaluationUnitKeyword_1() { return cEvaluationUnitKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('numberquestions' numberquestions=EInt)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'numberquestions'
		public Keyword getNumberquestionsKeyword_4_0() { return cNumberquestionsKeyword_4_0; }
		
		//numberquestions=EInt
		public Assignment getNumberquestionsAssignment_4_1() { return cNumberquestionsAssignment_4_1; }
		
		//EInt
		public RuleCall getNumberquestionsEIntParserRuleCall_4_1_0() { return cNumberquestionsEIntParserRuleCall_4_1_0; }
		
		//('questions' '{' questions+=Question ("," questions+=Question)* '}')?
		public Group getGroup_5() { return cGroup_5; }
		
		//'questions'
		public Keyword getQuestionsKeyword_5_0() { return cQuestionsKeyword_5_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_5_1() { return cLeftCurlyBracketKeyword_5_1; }
		
		//questions+=Question
		public Assignment getQuestionsAssignment_5_2() { return cQuestionsAssignment_5_2; }
		
		//Question
		public RuleCall getQuestionsQuestionParserRuleCall_5_2_0() { return cQuestionsQuestionParserRuleCall_5_2_0; }
		
		//("," questions+=Question)*
		public Group getGroup_5_3() { return cGroup_5_3; }
		
		//","
		public Keyword getCommaKeyword_5_3_0() { return cCommaKeyword_5_3_0; }
		
		//questions+=Question
		public Assignment getQuestionsAssignment_5_3_1() { return cQuestionsAssignment_5_3_1; }
		
		//Question
		public RuleCall getQuestionsQuestionParserRuleCall_5_3_1_0() { return cQuestionsQuestionParserRuleCall_5_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5_4() { return cRightCurlyBracketKeyword_5_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class Question_ImplElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.Upctformaevalua.Question_Impl");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cQuestionAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cQuestionKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cCorrectfeedbackKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cCorrectfeedbackAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cCorrectfeedbackEStringParserRuleCall_3_1_0 = (RuleCall)cCorrectfeedbackAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cIncorrectfeedbackKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cIncorrectfeedbackAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cIncorrectfeedbackEStringParserRuleCall_4_1_0 = (RuleCall)cIncorrectfeedbackAssignment_4_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Question_Impl Question:
		//	{Question}
		//	'Question'
		//	'{' ('correctfeedback' correctfeedback=EString)? ('incorrectfeedback' incorrectfeedback=EString)?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Question} 'Question' '{' ('correctfeedback' correctfeedback=EString)? ('incorrectfeedback' incorrectfeedback=EString)?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{Question}
		public Action getQuestionAction_0() { return cQuestionAction_0; }
		
		//'Question'
		public Keyword getQuestionKeyword_1() { return cQuestionKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('correctfeedback' correctfeedback=EString)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'correctfeedback'
		public Keyword getCorrectfeedbackKeyword_3_0() { return cCorrectfeedbackKeyword_3_0; }
		
		//correctfeedback=EString
		public Assignment getCorrectfeedbackAssignment_3_1() { return cCorrectfeedbackAssignment_3_1; }
		
		//EString
		public RuleCall getCorrectfeedbackEStringParserRuleCall_3_1_0() { return cCorrectfeedbackEStringParserRuleCall_3_1_0; }
		
		//('incorrectfeedback' incorrectfeedback=EString)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'incorrectfeedback'
		public Keyword getIncorrectfeedbackKeyword_4_0() { return cIncorrectfeedbackKeyword_4_0; }
		
		//incorrectfeedback=EString
		public Assignment getIncorrectfeedbackAssignment_4_1() { return cIncorrectfeedbackAssignment_4_1; }
		
		//EString
		public RuleCall getIncorrectfeedbackEStringParserRuleCall_4_1_0() { return cIncorrectfeedbackEStringParserRuleCall_4_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class EIntElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.Upctformaevalua.EInt");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		
		//EInt ecore::EInt:
		//	'-'? INT;
		@Override public ParserRule getRule() { return rule; }
		
		//'-'? INT
		public Group getGroup() { return cGroup; }
		
		//'-'?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
	}
	public class TrainingElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.Upctformaevalua.Training");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cTrainingAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cTrainingKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cNumberquestionsKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cNumberquestionsAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cNumberquestionsEIntParserRuleCall_4_1_0 = (RuleCall)cNumberquestionsAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cAttemptsKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cAttemptsAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cAttemptsEIntParserRuleCall_5_1_0 = (RuleCall)cAttemptsAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cGradeKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cGradeAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cGradeTypeGradeEnumRuleCall_6_1_0 = (RuleCall)cGradeAssignment_6_1.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cQuestionsKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_7_1 = (Keyword)cGroup_7.eContents().get(1);
		private final Assignment cQuestionsAssignment_7_2 = (Assignment)cGroup_7.eContents().get(2);
		private final RuleCall cQuestionsQuestionParserRuleCall_7_2_0 = (RuleCall)cQuestionsAssignment_7_2.eContents().get(0);
		private final Group cGroup_7_3 = (Group)cGroup_7.eContents().get(3);
		private final Keyword cCommaKeyword_7_3_0 = (Keyword)cGroup_7_3.eContents().get(0);
		private final Assignment cQuestionsAssignment_7_3_1 = (Assignment)cGroup_7_3.eContents().get(1);
		private final RuleCall cQuestionsQuestionParserRuleCall_7_3_1_0 = (RuleCall)cQuestionsAssignment_7_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7_4 = (Keyword)cGroup_7.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//Training:
		//	{Training}
		//	'Training'
		//	name=EString
		//	'{' ('numberquestions' numberquestions=EInt)? ('Attempts' Attempts=EInt)? ('grade' grade=TypeGrade)? ('questions' '{'
		//	questions+=Question ("," questions+=Question)* '}')?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Training} 'Training' name=EString '{' ('numberquestions' numberquestions=EInt)? ('Attempts' Attempts=EInt)? ('grade'
		//grade=TypeGrade)? ('questions' '{' questions+=Question ("," questions+=Question)* '}')? '}'
		public Group getGroup() { return cGroup; }
		
		//{Training}
		public Action getTrainingAction_0() { return cTrainingAction_0; }
		
		//'Training'
		public Keyword getTrainingKeyword_1() { return cTrainingKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('numberquestions' numberquestions=EInt)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'numberquestions'
		public Keyword getNumberquestionsKeyword_4_0() { return cNumberquestionsKeyword_4_0; }
		
		//numberquestions=EInt
		public Assignment getNumberquestionsAssignment_4_1() { return cNumberquestionsAssignment_4_1; }
		
		//EInt
		public RuleCall getNumberquestionsEIntParserRuleCall_4_1_0() { return cNumberquestionsEIntParserRuleCall_4_1_0; }
		
		//('Attempts' Attempts=EInt)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'Attempts'
		public Keyword getAttemptsKeyword_5_0() { return cAttemptsKeyword_5_0; }
		
		//Attempts=EInt
		public Assignment getAttemptsAssignment_5_1() { return cAttemptsAssignment_5_1; }
		
		//EInt
		public RuleCall getAttemptsEIntParserRuleCall_5_1_0() { return cAttemptsEIntParserRuleCall_5_1_0; }
		
		//('grade' grade=TypeGrade)?
		public Group getGroup_6() { return cGroup_6; }
		
		//'grade'
		public Keyword getGradeKeyword_6_0() { return cGradeKeyword_6_0; }
		
		//grade=TypeGrade
		public Assignment getGradeAssignment_6_1() { return cGradeAssignment_6_1; }
		
		//TypeGrade
		public RuleCall getGradeTypeGradeEnumRuleCall_6_1_0() { return cGradeTypeGradeEnumRuleCall_6_1_0; }
		
		//('questions' '{' questions+=Question ("," questions+=Question)* '}')?
		public Group getGroup_7() { return cGroup_7; }
		
		//'questions'
		public Keyword getQuestionsKeyword_7_0() { return cQuestionsKeyword_7_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_7_1() { return cLeftCurlyBracketKeyword_7_1; }
		
		//questions+=Question
		public Assignment getQuestionsAssignment_7_2() { return cQuestionsAssignment_7_2; }
		
		//Question
		public RuleCall getQuestionsQuestionParserRuleCall_7_2_0() { return cQuestionsQuestionParserRuleCall_7_2_0; }
		
		//("," questions+=Question)*
		public Group getGroup_7_3() { return cGroup_7_3; }
		
		//","
		public Keyword getCommaKeyword_7_3_0() { return cCommaKeyword_7_3_0; }
		
		//questions+=Question
		public Assignment getQuestionsAssignment_7_3_1() { return cQuestionsAssignment_7_3_1; }
		
		//Question
		public RuleCall getQuestionsQuestionParserRuleCall_7_3_1_0() { return cQuestionsQuestionParserRuleCall_7_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7_4() { return cRightCurlyBracketKeyword_7_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}
	public class FinalElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.Upctformaevalua.Final");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cFinalAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cFinalKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cNumberquestionsKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cNumberquestionsAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cNumberquestionsEIntParserRuleCall_4_1_0 = (RuleCall)cNumberquestionsAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cQuestionsKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cQuestionsAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final RuleCall cQuestionsQuestionParserRuleCall_5_2_0 = (RuleCall)cQuestionsAssignment_5_2.eContents().get(0);
		private final Group cGroup_5_3 = (Group)cGroup_5.eContents().get(3);
		private final Keyword cCommaKeyword_5_3_0 = (Keyword)cGroup_5_3.eContents().get(0);
		private final Assignment cQuestionsAssignment_5_3_1 = (Assignment)cGroup_5_3.eContents().get(1);
		private final RuleCall cQuestionsQuestionParserRuleCall_5_3_1_0 = (RuleCall)cQuestionsAssignment_5_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5_4 = (Keyword)cGroup_5.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//Final:
		//	{Final}
		//	'Final'
		//	name=EString
		//	'{' ('numberquestions' numberquestions=EInt)? ('questions' '{' questions+=Question ("," questions+=Question)* '}')?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Final} 'Final' name=EString '{' ('numberquestions' numberquestions=EInt)? ('questions' '{' questions+=Question (","
		//questions+=Question)* '}')? '}'
		public Group getGroup() { return cGroup; }
		
		//{Final}
		public Action getFinalAction_0() { return cFinalAction_0; }
		
		//'Final'
		public Keyword getFinalKeyword_1() { return cFinalKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('numberquestions' numberquestions=EInt)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'numberquestions'
		public Keyword getNumberquestionsKeyword_4_0() { return cNumberquestionsKeyword_4_0; }
		
		//numberquestions=EInt
		public Assignment getNumberquestionsAssignment_4_1() { return cNumberquestionsAssignment_4_1; }
		
		//EInt
		public RuleCall getNumberquestionsEIntParserRuleCall_4_1_0() { return cNumberquestionsEIntParserRuleCall_4_1_0; }
		
		//('questions' '{' questions+=Question ("," questions+=Question)* '}')?
		public Group getGroup_5() { return cGroup_5; }
		
		//'questions'
		public Keyword getQuestionsKeyword_5_0() { return cQuestionsKeyword_5_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_5_1() { return cLeftCurlyBracketKeyword_5_1; }
		
		//questions+=Question
		public Assignment getQuestionsAssignment_5_2() { return cQuestionsAssignment_5_2; }
		
		//Question
		public RuleCall getQuestionsQuestionParserRuleCall_5_2_0() { return cQuestionsQuestionParserRuleCall_5_2_0; }
		
		//("," questions+=Question)*
		public Group getGroup_5_3() { return cGroup_5_3; }
		
		//","
		public Keyword getCommaKeyword_5_3_0() { return cCommaKeyword_5_3_0; }
		
		//questions+=Question
		public Assignment getQuestionsAssignment_5_3_1() { return cQuestionsAssignment_5_3_1; }
		
		//Question
		public RuleCall getQuestionsQuestionParserRuleCall_5_3_1_0() { return cQuestionsQuestionParserRuleCall_5_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5_4() { return cRightCurlyBracketKeyword_5_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class UniqueAnswerElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.Upctformaevalua.UniqueAnswer");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cUniqueAnswerKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cStatementKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cStatementsAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cStatementsParagraphParserRuleCall_3_0 = (RuleCall)cStatementsAssignment_3.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cAnswersKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cAnswersAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final RuleCall cAnswersUniqueParserRuleCall_4_2_0 = (RuleCall)cAnswersAssignment_4_2.eContents().get(0);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cAnswersAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final RuleCall cAnswersUniqueParserRuleCall_4_3_1_0 = (RuleCall)cAnswersAssignment_4_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cCorrectKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cCorrectanswerAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cCorrectanswerEIntParserRuleCall_5_1_0 = (RuleCall)cCorrectanswerAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cCorrectfeedbackKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cCorrectfeedbackAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cCorrectfeedbackEStringParserRuleCall_6_1_0 = (RuleCall)cCorrectfeedbackAssignment_6_1.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cIncorrectfeedbackKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cIncorrectfeedbackAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cIncorrectfeedbackEStringParserRuleCall_7_1_0 = (RuleCall)cIncorrectfeedbackAssignment_7_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//UniqueAnswer:
		//	'UniqueAnswer'
		//	'{'
		//	'statement' statements=Paragraph ('answers' '{' answers+=Unique ("," answers+=Unique)* '}')? ('correct'
		//	correctanswer=EInt)? ('correctfeedback' correctfeedback=EString)? ('incorrectfeedback' incorrectfeedback=EString)?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'UniqueAnswer' '{' 'statement' statements=Paragraph ('answers' '{' answers+=Unique ("," answers+=Unique)* '}')?
		//('correct' correctanswer=EInt)? ('correctfeedback' correctfeedback=EString)? ('incorrectfeedback'
		//incorrectfeedback=EString)? '}'
		public Group getGroup() { return cGroup; }
		
		//'UniqueAnswer'
		public Keyword getUniqueAnswerKeyword_0() { return cUniqueAnswerKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'statement'
		public Keyword getStatementKeyword_2() { return cStatementKeyword_2; }
		
		//statements=Paragraph
		public Assignment getStatementsAssignment_3() { return cStatementsAssignment_3; }
		
		//Paragraph
		public RuleCall getStatementsParagraphParserRuleCall_3_0() { return cStatementsParagraphParserRuleCall_3_0; }
		
		//('answers' '{' answers+=Unique ("," answers+=Unique)* '}')?
		public Group getGroup_4() { return cGroup_4; }
		
		//'answers'
		public Keyword getAnswersKeyword_4_0() { return cAnswersKeyword_4_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_4_1() { return cLeftCurlyBracketKeyword_4_1; }
		
		//answers+=Unique
		public Assignment getAnswersAssignment_4_2() { return cAnswersAssignment_4_2; }
		
		//Unique
		public RuleCall getAnswersUniqueParserRuleCall_4_2_0() { return cAnswersUniqueParserRuleCall_4_2_0; }
		
		//("," answers+=Unique)*
		public Group getGroup_4_3() { return cGroup_4_3; }
		
		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }
		
		//answers+=Unique
		public Assignment getAnswersAssignment_4_3_1() { return cAnswersAssignment_4_3_1; }
		
		//Unique
		public RuleCall getAnswersUniqueParserRuleCall_4_3_1_0() { return cAnswersUniqueParserRuleCall_4_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4_4() { return cRightCurlyBracketKeyword_4_4; }
		
		//('correct' correctanswer=EInt)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'correct'
		public Keyword getCorrectKeyword_5_0() { return cCorrectKeyword_5_0; }
		
		//correctanswer=EInt
		public Assignment getCorrectanswerAssignment_5_1() { return cCorrectanswerAssignment_5_1; }
		
		//EInt
		public RuleCall getCorrectanswerEIntParserRuleCall_5_1_0() { return cCorrectanswerEIntParserRuleCall_5_1_0; }
		
		//('correctfeedback' correctfeedback=EString)?
		public Group getGroup_6() { return cGroup_6; }
		
		//'correctfeedback'
		public Keyword getCorrectfeedbackKeyword_6_0() { return cCorrectfeedbackKeyword_6_0; }
		
		//correctfeedback=EString
		public Assignment getCorrectfeedbackAssignment_6_1() { return cCorrectfeedbackAssignment_6_1; }
		
		//EString
		public RuleCall getCorrectfeedbackEStringParserRuleCall_6_1_0() { return cCorrectfeedbackEStringParserRuleCall_6_1_0; }
		
		//('incorrectfeedback' incorrectfeedback=EString)?
		public Group getGroup_7() { return cGroup_7; }
		
		//'incorrectfeedback'
		public Keyword getIncorrectfeedbackKeyword_7_0() { return cIncorrectfeedbackKeyword_7_0; }
		
		//incorrectfeedback=EString
		public Assignment getIncorrectfeedbackAssignment_7_1() { return cIncorrectfeedbackAssignment_7_1; }
		
		//EString
		public RuleCall getIncorrectfeedbackEStringParserRuleCall_7_1_0() { return cIncorrectfeedbackEStringParserRuleCall_7_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}
	public class MultipleAnswerElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.Upctformaevalua.MultipleAnswer");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cMultipleAnswerKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cStatementsKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cStatementsAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cStatementsParagraphParserRuleCall_3_0 = (RuleCall)cStatementsAssignment_3.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cAnswersKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cAnswersAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final RuleCall cAnswersMultipleParserRuleCall_4_2_0 = (RuleCall)cAnswersAssignment_4_2.eContents().get(0);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cAnswersAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final RuleCall cAnswersMultipleParserRuleCall_4_3_1_0 = (RuleCall)cAnswersAssignment_4_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cCorrectfeedbackKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cCorrectfeedbackAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cCorrectfeedbackEStringParserRuleCall_5_1_0 = (RuleCall)cCorrectfeedbackAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cIncorrectfeedbackKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cIncorrectfeedbackAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cIncorrectfeedbackEStringParserRuleCall_6_1_0 = (RuleCall)cIncorrectfeedbackAssignment_6_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//MultipleAnswer:
		//	'MultipleAnswer'
		//	'{'
		//	'statements' statements=Paragraph ('answers' '{' answers+=Multiple ("," answers+=Multiple)* '}')? ('correctfeedback'
		//	correctfeedback=EString)? ('incorrectfeedback' incorrectfeedback=EString)?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'MultipleAnswer' '{' 'statements' statements=Paragraph ('answers' '{' answers+=Multiple ("," answers+=Multiple)* '}')?
		//('correctfeedback' correctfeedback=EString)? ('incorrectfeedback' incorrectfeedback=EString)? '}'
		public Group getGroup() { return cGroup; }
		
		//'MultipleAnswer'
		public Keyword getMultipleAnswerKeyword_0() { return cMultipleAnswerKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'statements'
		public Keyword getStatementsKeyword_2() { return cStatementsKeyword_2; }
		
		//statements=Paragraph
		public Assignment getStatementsAssignment_3() { return cStatementsAssignment_3; }
		
		//Paragraph
		public RuleCall getStatementsParagraphParserRuleCall_3_0() { return cStatementsParagraphParserRuleCall_3_0; }
		
		//('answers' '{' answers+=Multiple ("," answers+=Multiple)* '}')?
		public Group getGroup_4() { return cGroup_4; }
		
		//'answers'
		public Keyword getAnswersKeyword_4_0() { return cAnswersKeyword_4_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_4_1() { return cLeftCurlyBracketKeyword_4_1; }
		
		//answers+=Multiple
		public Assignment getAnswersAssignment_4_2() { return cAnswersAssignment_4_2; }
		
		//Multiple
		public RuleCall getAnswersMultipleParserRuleCall_4_2_0() { return cAnswersMultipleParserRuleCall_4_2_0; }
		
		//("," answers+=Multiple)*
		public Group getGroup_4_3() { return cGroup_4_3; }
		
		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }
		
		//answers+=Multiple
		public Assignment getAnswersAssignment_4_3_1() { return cAnswersAssignment_4_3_1; }
		
		//Multiple
		public RuleCall getAnswersMultipleParserRuleCall_4_3_1_0() { return cAnswersMultipleParserRuleCall_4_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4_4() { return cRightCurlyBracketKeyword_4_4; }
		
		//('correctfeedback' correctfeedback=EString)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'correctfeedback'
		public Keyword getCorrectfeedbackKeyword_5_0() { return cCorrectfeedbackKeyword_5_0; }
		
		//correctfeedback=EString
		public Assignment getCorrectfeedbackAssignment_5_1() { return cCorrectfeedbackAssignment_5_1; }
		
		//EString
		public RuleCall getCorrectfeedbackEStringParserRuleCall_5_1_0() { return cCorrectfeedbackEStringParserRuleCall_5_1_0; }
		
		//('incorrectfeedback' incorrectfeedback=EString)?
		public Group getGroup_6() { return cGroup_6; }
		
		//'incorrectfeedback'
		public Keyword getIncorrectfeedbackKeyword_6_0() { return cIncorrectfeedbackKeyword_6_0; }
		
		//incorrectfeedback=EString
		public Assignment getIncorrectfeedbackAssignment_6_1() { return cIncorrectfeedbackAssignment_6_1; }
		
		//EString
		public RuleCall getIncorrectfeedbackEStringParserRuleCall_6_1_0() { return cIncorrectfeedbackEStringParserRuleCall_6_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	public class FillingAnswerElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.Upctformaevalua.FillingAnswer");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cFillingAnswerAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cFillingAnswerKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cCorrectfeedbackKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cCorrectfeedbackAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cCorrectfeedbackEStringParserRuleCall_3_1_0 = (RuleCall)cCorrectfeedbackAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cIncorrectfeedbackKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cIncorrectfeedbackAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cIncorrectfeedbackEStringParserRuleCall_4_1_0 = (RuleCall)cIncorrectfeedbackAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cHolesKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cHolesAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final RuleCall cHolesHoleParserRuleCall_5_2_0 = (RuleCall)cHolesAssignment_5_2.eContents().get(0);
		private final Group cGroup_5_3 = (Group)cGroup_5.eContents().get(3);
		private final Keyword cCommaKeyword_5_3_0 = (Keyword)cGroup_5_3.eContents().get(0);
		private final Assignment cHolesAssignment_5_3_1 = (Assignment)cGroup_5_3.eContents().get(1);
		private final RuleCall cHolesHoleParserRuleCall_5_3_1_0 = (RuleCall)cHolesAssignment_5_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5_4 = (Keyword)cGroup_5.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//FillingAnswer:
		//	{FillingAnswer}
		//	'FillingAnswer'
		//	'{' ('correctfeedback' correctfeedback=EString)? ('incorrectfeedback' incorrectfeedback=EString)? ('holes' '{'
		//	holes+=Hole ("," holes+=Hole)* '}')?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{FillingAnswer} 'FillingAnswer' '{' ('correctfeedback' correctfeedback=EString)? ('incorrectfeedback'
		//incorrectfeedback=EString)? ('holes' '{' holes+=Hole ("," holes+=Hole)* '}')? '}'
		public Group getGroup() { return cGroup; }
		
		//{FillingAnswer}
		public Action getFillingAnswerAction_0() { return cFillingAnswerAction_0; }
		
		//'FillingAnswer'
		public Keyword getFillingAnswerKeyword_1() { return cFillingAnswerKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('correctfeedback' correctfeedback=EString)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'correctfeedback'
		public Keyword getCorrectfeedbackKeyword_3_0() { return cCorrectfeedbackKeyword_3_0; }
		
		//correctfeedback=EString
		public Assignment getCorrectfeedbackAssignment_3_1() { return cCorrectfeedbackAssignment_3_1; }
		
		//EString
		public RuleCall getCorrectfeedbackEStringParserRuleCall_3_1_0() { return cCorrectfeedbackEStringParserRuleCall_3_1_0; }
		
		//('incorrectfeedback' incorrectfeedback=EString)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'incorrectfeedback'
		public Keyword getIncorrectfeedbackKeyword_4_0() { return cIncorrectfeedbackKeyword_4_0; }
		
		//incorrectfeedback=EString
		public Assignment getIncorrectfeedbackAssignment_4_1() { return cIncorrectfeedbackAssignment_4_1; }
		
		//EString
		public RuleCall getIncorrectfeedbackEStringParserRuleCall_4_1_0() { return cIncorrectfeedbackEStringParserRuleCall_4_1_0; }
		
		//('holes' '{' holes+=Hole ("," holes+=Hole)* '}')?
		public Group getGroup_5() { return cGroup_5; }
		
		//'holes'
		public Keyword getHolesKeyword_5_0() { return cHolesKeyword_5_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_5_1() { return cLeftCurlyBracketKeyword_5_1; }
		
		//holes+=Hole
		public Assignment getHolesAssignment_5_2() { return cHolesAssignment_5_2; }
		
		//Hole
		public RuleCall getHolesHoleParserRuleCall_5_2_0() { return cHolesHoleParserRuleCall_5_2_0; }
		
		//("," holes+=Hole)*
		public Group getGroup_5_3() { return cGroup_5_3; }
		
		//","
		public Keyword getCommaKeyword_5_3_0() { return cCommaKeyword_5_3_0; }
		
		//holes+=Hole
		public Assignment getHolesAssignment_5_3_1() { return cHolesAssignment_5_3_1; }
		
		//Hole
		public RuleCall getHolesHoleParserRuleCall_5_3_1_0() { return cHolesHoleParserRuleCall_5_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5_4() { return cRightCurlyBracketKeyword_5_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class TrueOrFalseElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.Upctformaevalua.TrueOrFalse");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cTrueOrFalseAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cTrueOrFalseKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cCorrectfeedbackKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cCorrectfeedbackAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cCorrectfeedbackEStringParserRuleCall_3_1_0 = (RuleCall)cCorrectfeedbackAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cIncorrectfeedbackKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cIncorrectfeedbackAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cIncorrectfeedbackEStringParserRuleCall_4_1_0 = (RuleCall)cIncorrectfeedbackAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cAssertionsKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cAssertionsAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final RuleCall cAssertionsAssertionParserRuleCall_5_2_0 = (RuleCall)cAssertionsAssignment_5_2.eContents().get(0);
		private final Group cGroup_5_3 = (Group)cGroup_5.eContents().get(3);
		private final Keyword cCommaKeyword_5_3_0 = (Keyword)cGroup_5_3.eContents().get(0);
		private final Assignment cAssertionsAssignment_5_3_1 = (Assignment)cGroup_5_3.eContents().get(1);
		private final RuleCall cAssertionsAssertionParserRuleCall_5_3_1_0 = (RuleCall)cAssertionsAssignment_5_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5_4 = (Keyword)cGroup_5.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//TrueOrFalse:
		//	{TrueOrFalse}
		//	'TrueOrFalse'
		//	'{' ('correctfeedback' correctfeedback=EString)? ('incorrectfeedback' incorrectfeedback=EString)? ('assertions' '{'
		//	assertions+=Assertion ("," assertions+=Assertion)* '}')?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{TrueOrFalse} 'TrueOrFalse' '{' ('correctfeedback' correctfeedback=EString)? ('incorrectfeedback'
		//incorrectfeedback=EString)? ('assertions' '{' assertions+=Assertion ("," assertions+=Assertion)* '}')? '}'
		public Group getGroup() { return cGroup; }
		
		//{TrueOrFalse}
		public Action getTrueOrFalseAction_0() { return cTrueOrFalseAction_0; }
		
		//'TrueOrFalse'
		public Keyword getTrueOrFalseKeyword_1() { return cTrueOrFalseKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('correctfeedback' correctfeedback=EString)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'correctfeedback'
		public Keyword getCorrectfeedbackKeyword_3_0() { return cCorrectfeedbackKeyword_3_0; }
		
		//correctfeedback=EString
		public Assignment getCorrectfeedbackAssignment_3_1() { return cCorrectfeedbackAssignment_3_1; }
		
		//EString
		public RuleCall getCorrectfeedbackEStringParserRuleCall_3_1_0() { return cCorrectfeedbackEStringParserRuleCall_3_1_0; }
		
		//('incorrectfeedback' incorrectfeedback=EString)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'incorrectfeedback'
		public Keyword getIncorrectfeedbackKeyword_4_0() { return cIncorrectfeedbackKeyword_4_0; }
		
		//incorrectfeedback=EString
		public Assignment getIncorrectfeedbackAssignment_4_1() { return cIncorrectfeedbackAssignment_4_1; }
		
		//EString
		public RuleCall getIncorrectfeedbackEStringParserRuleCall_4_1_0() { return cIncorrectfeedbackEStringParserRuleCall_4_1_0; }
		
		//('assertions' '{' assertions+=Assertion ("," assertions+=Assertion)* '}')?
		public Group getGroup_5() { return cGroup_5; }
		
		//'assertions'
		public Keyword getAssertionsKeyword_5_0() { return cAssertionsKeyword_5_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_5_1() { return cLeftCurlyBracketKeyword_5_1; }
		
		//assertions+=Assertion
		public Assignment getAssertionsAssignment_5_2() { return cAssertionsAssignment_5_2; }
		
		//Assertion
		public RuleCall getAssertionsAssertionParserRuleCall_5_2_0() { return cAssertionsAssertionParserRuleCall_5_2_0; }
		
		//("," assertions+=Assertion)*
		public Group getGroup_5_3() { return cGroup_5_3; }
		
		//","
		public Keyword getCommaKeyword_5_3_0() { return cCommaKeyword_5_3_0; }
		
		//assertions+=Assertion
		public Assignment getAssertionsAssignment_5_3_1() { return cAssertionsAssignment_5_3_1; }
		
		//Assertion
		public RuleCall getAssertionsAssertionParserRuleCall_5_3_1_0() { return cAssertionsAssertionParserRuleCall_5_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5_4() { return cRightCurlyBracketKeyword_5_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class ParagraphElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.Upctformaevalua.Paragraph");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cParagraphAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cTextAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cTextEStringParserRuleCall_1_0 = (RuleCall)cTextAssignment_1.eContents().get(0);
		
		//Paragraph:
		//	{Paragraph} text=EString?;
		@Override public ParserRule getRule() { return rule; }
		
		//{Paragraph} text=EString?
		public Group getGroup() { return cGroup; }
		
		//{Paragraph}
		public Action getParagraphAction_0() { return cParagraphAction_0; }
		
		//text=EString?
		public Assignment getTextAssignment_1() { return cTextAssignment_1; }
		
		//EString
		public RuleCall getTextEStringParserRuleCall_1_0() { return cTextEStringParserRuleCall_1_0; }
	}
	public class UniqueElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.Upctformaevalua.Unique");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cUniqueAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cTextAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cTextEStringParserRuleCall_1_0 = (RuleCall)cTextAssignment_1.eContents().get(0);
		
		//Unique:
		//	{Unique} text=EString?;
		@Override public ParserRule getRule() { return rule; }
		
		//{Unique} text=EString?
		public Group getGroup() { return cGroup; }
		
		//{Unique}
		public Action getUniqueAction_0() { return cUniqueAction_0; }
		
		//text=EString?
		public Assignment getTextAssignment_1() { return cTextAssignment_1; }
		
		//EString
		public RuleCall getTextEStringParserRuleCall_1_0() { return cTextEStringParserRuleCall_1_0; }
	}
	public class MultipleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.Upctformaevalua.Multiple");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cMultipleAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cValueAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final Keyword cValueValueKeyword_1_0 = (Keyword)cValueAssignment_1.eContents().get(0);
		private final Keyword cMultipleKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cTextKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cTextAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cTextEStringParserRuleCall_4_1_0 = (RuleCall)cTextAssignment_4_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Multiple:
		//	{Multiple} value?='value'?
		//	'Multiple'
		//	'{' ('text' text=EString)?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Multiple} value?='value'? 'Multiple' '{' ('text' text=EString)? '}'
		public Group getGroup() { return cGroup; }
		
		//{Multiple}
		public Action getMultipleAction_0() { return cMultipleAction_0; }
		
		//value?='value'?
		public Assignment getValueAssignment_1() { return cValueAssignment_1; }
		
		//'value'
		public Keyword getValueValueKeyword_1_0() { return cValueValueKeyword_1_0; }
		
		//'Multiple'
		public Keyword getMultipleKeyword_2() { return cMultipleKeyword_2; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('text' text=EString)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'text'
		public Keyword getTextKeyword_4_0() { return cTextKeyword_4_0; }
		
		//text=EString
		public Assignment getTextAssignment_4_1() { return cTextAssignment_4_1; }
		
		//EString
		public RuleCall getTextEStringParserRuleCall_4_1_0() { return cTextEStringParserRuleCall_4_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class EBooleanElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.Upctformaevalua.EBoolean");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cTrueKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cFalseKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		
		//EBoolean ecore::EBoolean:
		//	'true' | 'false';
		@Override public ParserRule getRule() { return rule; }
		
		//'true' | 'false'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//'true'
		public Keyword getTrueKeyword_0() { return cTrueKeyword_0; }
		
		//'false'
		public Keyword getFalseKeyword_1() { return cFalseKeyword_1; }
	}
	public class HoleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.Upctformaevalua.Hole");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cHoleAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cHoleKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cTextKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cTextAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cTextEStringParserRuleCall_3_1_0 = (RuleCall)cTextAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cTypeKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cTypeAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cTypeTypeHoleEnumRuleCall_4_1_0 = (RuleCall)cTypeAssignment_4_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Hole:
		//	{Hole}
		//	'Hole'
		//	'{' ('text' text=EString)? ('type' type=TypeHole)?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Hole} 'Hole' '{' ('text' text=EString)? ('type' type=TypeHole)? '}'
		public Group getGroup() { return cGroup; }
		
		//{Hole}
		public Action getHoleAction_0() { return cHoleAction_0; }
		
		//'Hole'
		public Keyword getHoleKeyword_1() { return cHoleKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('text' text=EString)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'text'
		public Keyword getTextKeyword_3_0() { return cTextKeyword_3_0; }
		
		//text=EString
		public Assignment getTextAssignment_3_1() { return cTextAssignment_3_1; }
		
		//EString
		public RuleCall getTextEStringParserRuleCall_3_1_0() { return cTextEStringParserRuleCall_3_1_0; }
		
		//('type' type=TypeHole)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'type'
		public Keyword getTypeKeyword_4_0() { return cTypeKeyword_4_0; }
		
		//type=TypeHole
		public Assignment getTypeAssignment_4_1() { return cTypeAssignment_4_1; }
		
		//TypeHole
		public RuleCall getTypeTypeHoleEnumRuleCall_4_1_0() { return cTypeTypeHoleEnumRuleCall_4_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class AssertionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.Upctformaevalua.Assertion");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cAssertionAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cValueAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final Keyword cValueValueKeyword_1_0 = (Keyword)cValueAssignment_1.eContents().get(0);
		private final Keyword cAssertionKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cTextKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cTextAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cTextEStringParserRuleCall_4_1_0 = (RuleCall)cTextAssignment_4_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Assertion:
		//	{Assertion} value?='value'?
		//	'Assertion'
		//	'{' ('text' text=EString)?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Assertion} value?='value'? 'Assertion' '{' ('text' text=EString)? '}'
		public Group getGroup() { return cGroup; }
		
		//{Assertion}
		public Action getAssertionAction_0() { return cAssertionAction_0; }
		
		//value?='value'?
		public Assignment getValueAssignment_1() { return cValueAssignment_1; }
		
		//'value'
		public Keyword getValueValueKeyword_1_0() { return cValueValueKeyword_1_0; }
		
		//'Assertion'
		public Keyword getAssertionKeyword_2() { return cAssertionKeyword_2; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('text' text=EString)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'text'
		public Keyword getTextKeyword_4_0() { return cTextKeyword_4_0; }
		
		//text=EString
		public Assignment getTextAssignment_4_1() { return cTextAssignment_4_1; }
		
		//EString
		public RuleCall getTextEStringParserRuleCall_4_1_0() { return cTextEStringParserRuleCall_4_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	
	public class TypeHoleElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.Upctformaevalua.TypeHole");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cVisibleEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cVisibleVisibleKeyword_0_0 = (Keyword)cVisibleEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cHoleEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cHoleHoleKeyword_1_0 = (Keyword)cHoleEnumLiteralDeclaration_1.eContents().get(0);
		
		//enum TypeHole:
		//	visible | hole;
		public EnumRule getRule() { return rule; }
		
		//visible | hole
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//visible
		public EnumLiteralDeclaration getVisibleEnumLiteralDeclaration_0() { return cVisibleEnumLiteralDeclaration_0; }
		
		//'visible'
		public Keyword getVisibleVisibleKeyword_0_0() { return cVisibleVisibleKeyword_0_0; }
		
		//hole
		public EnumLiteralDeclaration getHoleEnumLiteralDeclaration_1() { return cHoleEnumLiteralDeclaration_1; }
		
		//'hole'
		public Keyword getHoleHoleKeyword_1_0() { return cHoleHoleKeyword_1_0; }
	}
	public class TypeGradeElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.Upctformaevalua.TypeGrade");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cHighestEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cHighestHighestKeyword_0_0 = (Keyword)cHighestEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cMiddleEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cMiddleMiddleKeyword_1_0 = (Keyword)cMiddleEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cLowestEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cLowestLowestKeyword_2_0 = (Keyword)cLowestEnumLiteralDeclaration_2.eContents().get(0);
		
		//enum TypeGrade:
		//	highest | middle | lowest;
		public EnumRule getRule() { return rule; }
		
		//highest | middle | lowest
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//highest
		public EnumLiteralDeclaration getHighestEnumLiteralDeclaration_0() { return cHighestEnumLiteralDeclaration_0; }
		
		//'highest'
		public Keyword getHighestHighestKeyword_0_0() { return cHighestHighestKeyword_0_0; }
		
		//middle
		public EnumLiteralDeclaration getMiddleEnumLiteralDeclaration_1() { return cMiddleEnumLiteralDeclaration_1; }
		
		//'middle'
		public Keyword getMiddleMiddleKeyword_1_0() { return cMiddleMiddleKeyword_1_0; }
		
		//lowest
		public EnumLiteralDeclaration getLowestEnumLiteralDeclaration_2() { return cLowestEnumLiteralDeclaration_2; }
		
		//'lowest'
		public Keyword getLowestLowestKeyword_2_0() { return cLowestLowestKeyword_2_0; }
	}
	
	private final EvaluationElements pEvaluation;
	private final QualifiedNameElements pQualifiedName;
	private final EvaluationUnitElements pEvaluationUnit;
	private final QuestionElements pQuestion;
	private final EStringElements pEString;
	private final EvaluationUnit_ImplElements pEvaluationUnit_Impl;
	private final Question_ImplElements pQuestion_Impl;
	private final EIntElements pEInt;
	private final TrainingElements pTraining;
	private final FinalElements pFinal;
	private final UniqueAnswerElements pUniqueAnswer;
	private final MultipleAnswerElements pMultipleAnswer;
	private final FillingAnswerElements pFillingAnswer;
	private final TrueOrFalseElements pTrueOrFalse;
	private final ParagraphElements pParagraph;
	private final UniqueElements pUnique;
	private final MultipleElements pMultiple;
	private final EBooleanElements pEBoolean;
	private final HoleElements pHole;
	private final TypeHoleElements eTypeHole;
	private final AssertionElements pAssertion;
	private final TypeGradeElements eTypeGrade;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public UpctformaevaluaGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pEvaluation = new EvaluationElements();
		this.pQualifiedName = new QualifiedNameElements();
		this.pEvaluationUnit = new EvaluationUnitElements();
		this.pQuestion = new QuestionElements();
		this.pEString = new EStringElements();
		this.pEvaluationUnit_Impl = new EvaluationUnit_ImplElements();
		this.pQuestion_Impl = new Question_ImplElements();
		this.pEInt = new EIntElements();
		this.pTraining = new TrainingElements();
		this.pFinal = new FinalElements();
		this.pUniqueAnswer = new UniqueAnswerElements();
		this.pMultipleAnswer = new MultipleAnswerElements();
		this.pFillingAnswer = new FillingAnswerElements();
		this.pTrueOrFalse = new TrueOrFalseElements();
		this.pParagraph = new ParagraphElements();
		this.pUnique = new UniqueElements();
		this.pMultiple = new MultipleElements();
		this.pEBoolean = new EBooleanElements();
		this.pHole = new HoleElements();
		this.eTypeHole = new TypeHoleElements();
		this.pAssertion = new AssertionElements();
		this.eTypeGrade = new TypeGradeElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.xtext.Upctformaevalua".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Evaluation:
	//	{Evaluation}
	//	'Evaluation'
	//	name=EString
	//	'{' ('package' name=QualifiedName ';')? (units+=EvaluationUnit ("," units+=EvaluationUnit)*)?
	//	'}';
	public EvaluationElements getEvaluationAccess() {
		return pEvaluation;
	}
	
	public ParserRule getEvaluationRule() {
		return getEvaluationAccess().getRule();
	}
	
	//QualifiedName:
	//	ID ('.' ID)*;
	public QualifiedNameElements getQualifiedNameAccess() {
		return pQualifiedName;
	}
	
	public ParserRule getQualifiedNameRule() {
		return getQualifiedNameAccess().getRule();
	}
	
	//EvaluationUnit:
	//	EvaluationUnit_Impl | Training | Final;
	public EvaluationUnitElements getEvaluationUnitAccess() {
		return pEvaluationUnit;
	}
	
	public ParserRule getEvaluationUnitRule() {
		return getEvaluationUnitAccess().getRule();
	}
	
	//Question:
	//	Question_Impl | UniqueAnswer | MultipleAnswer | FillingAnswer | TrueOrFalse;
	public QuestionElements getQuestionAccess() {
		return pQuestion;
	}
	
	public ParserRule getQuestionRule() {
		return getQuestionAccess().getRule();
	}
	
	//EString:
	//	STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//EvaluationUnit_Impl EvaluationUnit:
	//	{EvaluationUnit}
	//	'EvaluationUnit'
	//	name=EString
	//	'{' ('numberquestions' numberquestions=EInt)? ('questions' '{' questions+=Question ("," questions+=Question)* '}')?
	//	'}';
	public EvaluationUnit_ImplElements getEvaluationUnit_ImplAccess() {
		return pEvaluationUnit_Impl;
	}
	
	public ParserRule getEvaluationUnit_ImplRule() {
		return getEvaluationUnit_ImplAccess().getRule();
	}
	
	//Question_Impl Question:
	//	{Question}
	//	'Question'
	//	'{' ('correctfeedback' correctfeedback=EString)? ('incorrectfeedback' incorrectfeedback=EString)?
	//	'}';
	public Question_ImplElements getQuestion_ImplAccess() {
		return pQuestion_Impl;
	}
	
	public ParserRule getQuestion_ImplRule() {
		return getQuestion_ImplAccess().getRule();
	}
	
	//EInt ecore::EInt:
	//	'-'? INT;
	public EIntElements getEIntAccess() {
		return pEInt;
	}
	
	public ParserRule getEIntRule() {
		return getEIntAccess().getRule();
	}
	
	//Training:
	//	{Training}
	//	'Training'
	//	name=EString
	//	'{' ('numberquestions' numberquestions=EInt)? ('Attempts' Attempts=EInt)? ('grade' grade=TypeGrade)? ('questions' '{'
	//	questions+=Question ("," questions+=Question)* '}')?
	//	'}';
	public TrainingElements getTrainingAccess() {
		return pTraining;
	}
	
	public ParserRule getTrainingRule() {
		return getTrainingAccess().getRule();
	}
	
	//Final:
	//	{Final}
	//	'Final'
	//	name=EString
	//	'{' ('numberquestions' numberquestions=EInt)? ('questions' '{' questions+=Question ("," questions+=Question)* '}')?
	//	'}';
	public FinalElements getFinalAccess() {
		return pFinal;
	}
	
	public ParserRule getFinalRule() {
		return getFinalAccess().getRule();
	}
	
	//UniqueAnswer:
	//	'UniqueAnswer'
	//	'{'
	//	'statement' statements=Paragraph ('answers' '{' answers+=Unique ("," answers+=Unique)* '}')? ('correct'
	//	correctanswer=EInt)? ('correctfeedback' correctfeedback=EString)? ('incorrectfeedback' incorrectfeedback=EString)?
	//	'}';
	public UniqueAnswerElements getUniqueAnswerAccess() {
		return pUniqueAnswer;
	}
	
	public ParserRule getUniqueAnswerRule() {
		return getUniqueAnswerAccess().getRule();
	}
	
	//MultipleAnswer:
	//	'MultipleAnswer'
	//	'{'
	//	'statements' statements=Paragraph ('answers' '{' answers+=Multiple ("," answers+=Multiple)* '}')? ('correctfeedback'
	//	correctfeedback=EString)? ('incorrectfeedback' incorrectfeedback=EString)?
	//	'}';
	public MultipleAnswerElements getMultipleAnswerAccess() {
		return pMultipleAnswer;
	}
	
	public ParserRule getMultipleAnswerRule() {
		return getMultipleAnswerAccess().getRule();
	}
	
	//FillingAnswer:
	//	{FillingAnswer}
	//	'FillingAnswer'
	//	'{' ('correctfeedback' correctfeedback=EString)? ('incorrectfeedback' incorrectfeedback=EString)? ('holes' '{'
	//	holes+=Hole ("," holes+=Hole)* '}')?
	//	'}';
	public FillingAnswerElements getFillingAnswerAccess() {
		return pFillingAnswer;
	}
	
	public ParserRule getFillingAnswerRule() {
		return getFillingAnswerAccess().getRule();
	}
	
	//TrueOrFalse:
	//	{TrueOrFalse}
	//	'TrueOrFalse'
	//	'{' ('correctfeedback' correctfeedback=EString)? ('incorrectfeedback' incorrectfeedback=EString)? ('assertions' '{'
	//	assertions+=Assertion ("," assertions+=Assertion)* '}')?
	//	'}';
	public TrueOrFalseElements getTrueOrFalseAccess() {
		return pTrueOrFalse;
	}
	
	public ParserRule getTrueOrFalseRule() {
		return getTrueOrFalseAccess().getRule();
	}
	
	//Paragraph:
	//	{Paragraph} text=EString?;
	public ParagraphElements getParagraphAccess() {
		return pParagraph;
	}
	
	public ParserRule getParagraphRule() {
		return getParagraphAccess().getRule();
	}
	
	//Unique:
	//	{Unique} text=EString?;
	public UniqueElements getUniqueAccess() {
		return pUnique;
	}
	
	public ParserRule getUniqueRule() {
		return getUniqueAccess().getRule();
	}
	
	//Multiple:
	//	{Multiple} value?='value'?
	//	'Multiple'
	//	'{' ('text' text=EString)?
	//	'}';
	public MultipleElements getMultipleAccess() {
		return pMultiple;
	}
	
	public ParserRule getMultipleRule() {
		return getMultipleAccess().getRule();
	}
	
	//EBoolean ecore::EBoolean:
	//	'true' | 'false';
	public EBooleanElements getEBooleanAccess() {
		return pEBoolean;
	}
	
	public ParserRule getEBooleanRule() {
		return getEBooleanAccess().getRule();
	}
	
	//Hole:
	//	{Hole}
	//	'Hole'
	//	'{' ('text' text=EString)? ('type' type=TypeHole)?
	//	'}';
	public HoleElements getHoleAccess() {
		return pHole;
	}
	
	public ParserRule getHoleRule() {
		return getHoleAccess().getRule();
	}
	
	//enum TypeHole:
	//	visible | hole;
	public TypeHoleElements getTypeHoleAccess() {
		return eTypeHole;
	}
	
	public EnumRule getTypeHoleRule() {
		return getTypeHoleAccess().getRule();
	}
	
	//Assertion:
	//	{Assertion} value?='value'?
	//	'Assertion'
	//	'{' ('text' text=EString)?
	//	'}';
	public AssertionElements getAssertionAccess() {
		return pAssertion;
	}
	
	public ParserRule getAssertionRule() {
		return getAssertionAccess().getRule();
	}
	
	//enum TypeGrade:
	//	highest | middle | lowest;
	public TypeGradeElements getTypeGradeAccess() {
		return eTypeGrade;
	}
	
	public EnumRule getTypeGradeRule() {
		return getTypeGradeAccess().getRule();
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' | "'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/*'->'*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
