/**
 * generated by Xtext 2.12.0
 */
package org.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.xtext.ui.AbstractUpctformaUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class UpctformaUiModule extends AbstractUpctformaUiModule {
  public UpctformaUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
