/*
 * generated by Xtext 2.12.0
 */
package org.xtext.ide.contentassist.antlr;

import com.google.inject.Inject;
import java.util.HashMap;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.xtext.ide.contentassist.antlr.internal.InternalUpctformaParser;
import org.xtext.services.UpctformaGrammarAccess;

public class UpctformaParser extends AbstractContentAssistParser {

	@Inject
	private UpctformaGrammarAccess grammarAccess;

	private Map<AbstractElement, String> nameMappings;

	@Override
	protected InternalUpctformaParser createParser() {
		InternalUpctformaParser result = new InternalUpctformaParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getTypeAccess().getAlternatives(), "rule__Type__Alternatives");
					put(grammarAccess.getContentElementAccess().getAlternatives(), "rule__ContentElement__Alternatives");
					put(grammarAccess.getCompositeTypeAccess().getAlternatives(), "rule__CompositeType__Alternatives");
					put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
					put(grammarAccess.getEPrimitiveTypesAccess().getAlternatives(), "rule__EPrimitiveTypes__Alternatives");
					put(grammarAccess.getContentDefinitionAccess().getGroup(), "rule__ContentDefinition__Group__0");
					put(grammarAccess.getContentDefinitionAccess().getGroup_4(), "rule__ContentDefinition__Group_4__0");
					put(grammarAccess.getContentDefinitionAccess().getGroup_5(), "rule__ContentDefinition__Group_5__0");
					put(grammarAccess.getContentDefinitionAccess().getGroup_5_1(), "rule__ContentDefinition__Group_5_1__0");
					put(grammarAccess.getContentDefinitionAccess().getGroup_6(), "rule__ContentDefinition__Group_6__0");
					put(grammarAccess.getContentDefinitionAccess().getGroup_6_3(), "rule__ContentDefinition__Group_6_3__0");
					put(grammarAccess.getContentDefinitionAccess().getGroup_7(), "rule__ContentDefinition__Group_7__0");
					put(grammarAccess.getContentDefinitionAccess().getGroup_7_3(), "rule__ContentDefinition__Group_7_3__0");
					put(grammarAccess.getQualifiedNameAccess().getGroup(), "rule__QualifiedName__Group__0");
					put(grammarAccess.getQualifiedNameAccess().getGroup_1(), "rule__QualifiedName__Group_1__0");
					put(grammarAccess.getImportAccess().getGroup(), "rule__Import__Group__0");
					put(grammarAccess.getQualifiedNameWithWildcardAccess().getGroup(), "rule__QualifiedNameWithWildcard__Group__0");
					put(grammarAccess.getTemplateDefAccess().getGroup(), "rule__TemplateDef__Group__0");
					put(grammarAccess.getTemplateDefAccess().getGroup_4(), "rule__TemplateDef__Group_4__0");
					put(grammarAccess.getTemplateDefAccess().getGroup_4_1(), "rule__TemplateDef__Group_4_1__0");
					put(grammarAccess.getUnitAccess().getGroup(), "rule__Unit__Group__0");
					put(grammarAccess.getUnitAccess().getGroup_5(), "rule__Unit__Group_5__0");
					put(grammarAccess.getType_ImplAccess().getGroup(), "rule__Type_Impl__Group__0");
					put(grammarAccess.getRowAccess().getGroup(), "rule__Row__Group__0");
					put(grammarAccess.getRowAccess().getGroup_3(), "rule__Row__Group_3__0");
					put(grammarAccess.getRowAccess().getGroup_3_1(), "rule__Row__Group_3_1__0");
					put(grammarAccess.getRowAccess().getGroup_4(), "rule__Row__Group_4__0");
					put(grammarAccess.getColumnAccess().getGroup(), "rule__Column__Group__0");
					put(grammarAccess.getColumnAccess().getGroup_3(), "rule__Column__Group_3__0");
					put(grammarAccess.getColumnAccess().getGroup_4(), "rule__Column__Group_4__0");
					put(grammarAccess.getColumnAccess().getGroup_4_1(), "rule__Column__Group_4_1__0");
					put(grammarAccess.getUseTemplateAccess().getGroup(), "rule__UseTemplate__Group__0");
					put(grammarAccess.getUseTemplateAccess().getGroup_2(), "rule__UseTemplate__Group_2__0");
					put(grammarAccess.getUseTemplateAccess().getGroup_2_2(), "rule__UseTemplate__Group_2_2__0");
					put(grammarAccess.getContentElement_ImplAccess().getGroup(), "rule__ContentElement_Impl__Group__0");
					put(grammarAccess.getImageAccess().getGroup(), "rule__Image__Group__0");
					put(grammarAccess.getImageAccess().getGroup_3(), "rule__Image__Group_3__0");
					put(grammarAccess.getWidgetAccess().getGroup(), "rule__Widget__Group__0");
					put(grammarAccess.getWidgetAccess().getGroup_4(), "rule__Widget__Group_4__0");
					put(grammarAccess.getWidgetAccess().getGroup_4_2(), "rule__Widget__Group_4_2__0");
					put(grammarAccess.getTextAccess().getGroup(), "rule__Text__Group__0");
					put(grammarAccess.getTextAccess().getGroup_3(), "rule__Text__Group_3__0");
					put(grammarAccess.getComposite_ImplAccess().getGroup(), "rule__Composite_Impl__Group__0");
					put(grammarAccess.getVideoAccess().getGroup(), "rule__Video__Group__0");
					put(grammarAccess.getVideoAccess().getGroup_3(), "rule__Video__Group_3__0");
					put(grammarAccess.getSimpleElement_ImplAccess().getGroup(), "rule__SimpleElement_Impl__Group__0");
					put(grammarAccess.getPlaceHolderAccess().getGroup(), "rule__PlaceHolder__Group__0");
					put(grammarAccess.getGameAccess().getGroup(), "rule__Game__Group__0");
					put(grammarAccess.getGameAccess().getGroup_3(), "rule__Game__Group_3__0");
					put(grammarAccess.getFieldValueAccess().getGroup(), "rule__FieldValue__Group__0");
					put(grammarAccess.getRecordValueAccess().getGroup(), "rule__RecordValue__Group__0");
					put(grammarAccess.getRecordValueAccess().getGroup_2(), "rule__RecordValue__Group_2__0");
					put(grammarAccess.getListValueAccess().getGroup(), "rule__ListValue__Group__0");
					put(grammarAccess.getListValueAccess().getGroup_2(), "rule__ListValue__Group_2__0");
					put(grammarAccess.getWidgetTypeAccess().getGroup(), "rule__WidgetType__Group__0");
					put(grammarAccess.getWidgetTypeAccess().getGroup_5(), "rule__WidgetType__Group_5__0");
					put(grammarAccess.getCompositeType_ImplAccess().getGroup(), "rule__CompositeType_Impl__Group__0");
					put(grammarAccess.getParagraphAccess().getGroup(), "rule__Paragraph__Group__0");
					put(grammarAccess.getParagraphAccess().getGroup_1(), "rule__Paragraph__Group_1__0");
					put(grammarAccess.getSectionAccess().getGroup(), "rule__Section__Group__0");
					put(grammarAccess.getSectionAccess().getGroup_4(), "rule__Section__Group_4__0");
					put(grammarAccess.getSectionAccess().getGroup_5(), "rule__Section__Group_5__0");
					put(grammarAccess.getSectionAccess().getGroup_6(), "rule__Section__Group_6__0");
					put(grammarAccess.getSectionAccess().getGroup_6_1(), "rule__Section__Group_6_1__0");
					put(grammarAccess.getSimpleTypeAccess().getGroup(), "rule__SimpleType__Group__0");
					put(grammarAccess.getRecordTypeAccess().getGroup(), "rule__RecordType__Group__0");
					put(grammarAccess.getRecordTypeAccess().getGroup_3(), "rule__RecordType__Group_3__0");
					put(grammarAccess.getFieldAccess().getGroup(), "rule__Field__Group__0");
					put(grammarAccess.getListTypeAccess().getGroup(), "rule__ListType__Group__0");
					put(grammarAccess.getContentDefinitionAccess().getNameAssignment_2(), "rule__ContentDefinition__NameAssignment_2");
					put(grammarAccess.getContentDefinitionAccess().getNameAssignment_4_1(), "rule__ContentDefinition__NameAssignment_4_1");
					put(grammarAccess.getContentDefinitionAccess().getImportsAssignment_5_0(), "rule__ContentDefinition__ImportsAssignment_5_0");
					put(grammarAccess.getContentDefinitionAccess().getImportsAssignment_5_1_1(), "rule__ContentDefinition__ImportsAssignment_5_1_1");
					put(grammarAccess.getContentDefinitionAccess().getTypesAssignment_6_2(), "rule__ContentDefinition__TypesAssignment_6_2");
					put(grammarAccess.getContentDefinitionAccess().getTypesAssignment_6_3_1(), "rule__ContentDefinition__TypesAssignment_6_3_1");
					put(grammarAccess.getContentDefinitionAccess().getTemplatesAssignment_7_2(), "rule__ContentDefinition__TemplatesAssignment_7_2");
					put(grammarAccess.getContentDefinitionAccess().getTemplatesAssignment_7_3_1(), "rule__ContentDefinition__TemplatesAssignment_7_3_1");
					put(grammarAccess.getContentDefinitionAccess().getUnitAssignment_8(), "rule__ContentDefinition__UnitAssignment_8");
					put(grammarAccess.getImportAccess().getImportedNamespaceAssignment_1(), "rule__Import__ImportedNamespaceAssignment_1");
					put(grammarAccess.getTemplateDefAccess().getNameAssignment_2(), "rule__TemplateDef__NameAssignment_2");
					put(grammarAccess.getTemplateDefAccess().getRowsAssignment_4_0(), "rule__TemplateDef__RowsAssignment_4_0");
					put(grammarAccess.getTemplateDefAccess().getRowsAssignment_4_1_1(), "rule__TemplateDef__RowsAssignment_4_1_1");
					put(grammarAccess.getUnitAccess().getNameAssignment_1(), "rule__Unit__NameAssignment_1");
					put(grammarAccess.getUnitAccess().getAuthorAssignment_2(), "rule__Unit__AuthorAssignment_2");
					put(grammarAccess.getUnitAccess().getSectionsAssignment_4(), "rule__Unit__SectionsAssignment_4");
					put(grammarAccess.getUnitAccess().getSectionsAssignment_5_1(), "rule__Unit__SectionsAssignment_5_1");
					put(grammarAccess.getType_ImplAccess().getNameAssignment_2(), "rule__Type_Impl__NameAssignment_2");
					put(grammarAccess.getRowAccess().getColumnsAssignment_3_0(), "rule__Row__ColumnsAssignment_3_0");
					put(grammarAccess.getRowAccess().getColumnsAssignment_3_1_1(), "rule__Row__ColumnsAssignment_3_1_1");
					put(grammarAccess.getRowAccess().getUsetemplateAssignment_4_1(), "rule__Row__UsetemplateAssignment_4_1");
					put(grammarAccess.getColumnAccess().getWidthAssignment_3_1(), "rule__Column__WidthAssignment_3_1");
					put(grammarAccess.getColumnAccess().getElementsAssignment_4_0(), "rule__Column__ElementsAssignment_4_0");
					put(grammarAccess.getColumnAccess().getElementsAssignment_4_1_1(), "rule__Column__ElementsAssignment_4_1_1");
					put(grammarAccess.getUseTemplateAccess().getTypetemplateAssignment_1(), "rule__UseTemplate__TypetemplateAssignment_1");
					put(grammarAccess.getUseTemplateAccess().getTemplateelementsAssignment_2_1(), "rule__UseTemplate__TemplateelementsAssignment_2_1");
					put(grammarAccess.getUseTemplateAccess().getTemplateelementsAssignment_2_2_1(), "rule__UseTemplate__TemplateelementsAssignment_2_2_1");
					put(grammarAccess.getImageAccess().getUrlAssignment_3_1(), "rule__Image__UrlAssignment_3_1");
					put(grammarAccess.getWidgetAccess().getNameAssignment_1(), "rule__Widget__NameAssignment_1");
					put(grammarAccess.getWidgetAccess().getWidgettypeAssignment_3(), "rule__Widget__WidgettypeAssignment_3");
					put(grammarAccess.getWidgetAccess().getWidgetelementsAssignment_4_1(), "rule__Widget__WidgetelementsAssignment_4_1");
					put(grammarAccess.getWidgetAccess().getWidgetelementsAssignment_4_2_1(), "rule__Widget__WidgetelementsAssignment_4_2_1");
					put(grammarAccess.getTextAccess().getParagraphsAssignment_2(), "rule__Text__ParagraphsAssignment_2");
					put(grammarAccess.getTextAccess().getParagraphsAssignment_3_1(), "rule__Text__ParagraphsAssignment_3_1");
					put(grammarAccess.getVideoAccess().getIdAssignment_3_1(), "rule__Video__IdAssignment_3_1");
					put(grammarAccess.getPlaceHolderAccess().getTypeAssignment_1(), "rule__PlaceHolder__TypeAssignment_1");
					put(grammarAccess.getGameAccess().getIdAssignment_3_1(), "rule__Game__IdAssignment_3_1");
					put(grammarAccess.getFieldValueAccess().getNameAssignment_0(), "rule__FieldValue__NameAssignment_0");
					put(grammarAccess.getFieldValueAccess().getFieldvalueAssignment_2(), "rule__FieldValue__FieldvalueAssignment_2");
					put(grammarAccess.getRecordValueAccess().getRecordvaluesAssignment_1(), "rule__RecordValue__RecordvaluesAssignment_1");
					put(grammarAccess.getRecordValueAccess().getRecordvaluesAssignment_2_1(), "rule__RecordValue__RecordvaluesAssignment_2_1");
					put(grammarAccess.getListValueAccess().getListvaluesAssignment_1(), "rule__ListValue__ListvaluesAssignment_1");
					put(grammarAccess.getListValueAccess().getListvaluesAssignment_2_1(), "rule__ListValue__ListvaluesAssignment_2_1");
					put(grammarAccess.getWidgetTypeAccess().getNameAssignment_2(), "rule__WidgetType__NameAssignment_2");
					put(grammarAccess.getWidgetTypeAccess().getWidgettypeelementsAssignment_4(), "rule__WidgetType__WidgettypeelementsAssignment_4");
					put(grammarAccess.getWidgetTypeAccess().getWidgettypeelementsAssignment_5_1(), "rule__WidgetType__WidgettypeelementsAssignment_5_1");
					put(grammarAccess.getCompositeType_ImplAccess().getNameAssignment_2(), "rule__CompositeType_Impl__NameAssignment_2");
					put(grammarAccess.getParagraphAccess().getTextAssignment_1_1(), "rule__Paragraph__TextAssignment_1_1");
					put(grammarAccess.getSectionAccess().getNameAssignment_2(), "rule__Section__NameAssignment_2");
					put(grammarAccess.getSectionAccess().getImageAssignment_4_1(), "rule__Section__ImageAssignment_4_1");
					put(grammarAccess.getSectionAccess().getTitleAssignment_5_1(), "rule__Section__TitleAssignment_5_1");
					put(grammarAccess.getSectionAccess().getRowsAssignment_6_0(), "rule__Section__RowsAssignment_6_0");
					put(grammarAccess.getSectionAccess().getRowsAssignment_6_1_1(), "rule__Section__RowsAssignment_6_1_1");
					put(grammarAccess.getSimpleTypeAccess().getNameAssignment_1(), "rule__SimpleType__NameAssignment_1");
					put(grammarAccess.getRecordTypeAccess().getNameAssignment_0(), "rule__RecordType__NameAssignment_0");
					put(grammarAccess.getRecordTypeAccess().getRecordtypeAssignment_2(), "rule__RecordType__RecordtypeAssignment_2");
					put(grammarAccess.getRecordTypeAccess().getRecordtypeAssignment_3_1(), "rule__RecordType__RecordtypeAssignment_3_1");
					put(grammarAccess.getFieldAccess().getNameAssignment_0(), "rule__Field__NameAssignment_0");
					put(grammarAccess.getFieldAccess().getFieldtypeAssignment_2(), "rule__Field__FieldtypeAssignment_2");
					put(grammarAccess.getListTypeAccess().getNameAssignment_0(), "rule__ListType__NameAssignment_0");
					put(grammarAccess.getListTypeAccess().getListtypeAssignment_3(), "rule__ListType__ListtypeAssignment_3");
				}
			};
		}
		return nameMappings.get(element);
	}
			
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public UpctformaGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(UpctformaGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
