/**
 * generated by Xtext 2.12.0
 */
package org.xtext;

import org.xtext.UpctformaStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class UpctformaStandaloneSetup extends UpctformaStandaloneSetupGenerated {
  public static void doSetup() {
    new UpctformaStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
