/*
 * generated by Xtext 2.12.0
 */
package org.xtext.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.upctforma.ui.internal.UpctformaActivator;

public class UpctformaUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return UpctformaActivator.getInstance().getInjector("org.xtext.Upctforma");
	}

}
