/*
 * generated by Xtext 2.12.0
 */
package org.xtext.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.upctformagami.ui.internal.UpctformagamiActivator;

public class UpctformagamiUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return UpctformagamiActivator.getInstance().getInjector("org.xtext.Upctformagami");
	}

}
