/**
 * generated by Xtext 2.12.0
 */
package org.xtext;

import org.xtext.UpctformaevaluaStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class UpctformaevaluaStandaloneSetup extends UpctformaevaluaStandaloneSetupGenerated {
  public static void doSetup() {
    new UpctformaevaluaStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
