/**
 * generated by Xtext 2.12.0
 */
package org.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.xtext.ui.AbstractUpctformaevaluaUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class UpctformaevaluaUiModule extends AbstractUpctformaevaluaUiModule {
  public UpctformaevaluaUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
