/*
 * generated by Xtext 2.12.0
 */
package org.xtext.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.parser.antlr.internal.InternalUpctformaevaluaParser;
import org.xtext.services.UpctformaevaluaGrammarAccess;

public class UpctformaevaluaParser extends AbstractAntlrParser {

	@Inject
	private UpctformaevaluaGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalUpctformaevaluaParser createParser(XtextTokenStream stream) {
		return new InternalUpctformaevaluaParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Evaluation";
	}

	public UpctformaevaluaGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(UpctformaevaluaGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
